name: CI

on: [push, pull_request]

jobs:
  api:
    name: API Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.0

      - name: Install dependencies for API
        working-directory: ./api
        run: npm ci
      
      - name: Lint for API
        working-directory: ./api
        run: npm run lint

      - name: Run API tests
        working-directory: ./api
        run: npm test

      - name: Upload API code coverage 
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-api
          path: api/coverage/

  app:
    name: App Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.0

      - name: Install Vue.js CLI
        run: npm install -g @vue/cli

      - name: Install app dependencies
        working-directory: ./app
        run: npm ci
      
      - name: Lint for app
        working-directory: ./app
        run: npm run lint

      - name: Run app tests
        working-directory: ./app
        run: npm test

      - name: Upload code coverage for app
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-app
          path: app/coverage

  code-analysis:
    needs: [api, app]
    name: Code Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download code coverage results for API
        uses: actions/download-artifact@v2
        with:
          name: code-coverage-api
          path: api/coverage

      - name: Download code coverage results for app
        uses: actions/download-artifact@v2
        with:
          name: code-coverage-app
          path: app/coverage

      - name: CodeCov upload
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: api/coverage/lcov.info,app/coverage/lcov.info
          flags: unittests
          fail_ci_if_error: true
          verbose: true

      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any info
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
